### ISSUE TITLE
Provide ARM64 support

### ISSUE THREAD

**Issue by kchobantonov** [coder/enterprise-helm#241]
Followed the install steps (using helm 3)

kubectl create namespace coder
kubectl config set-context --current --namespace=coder
helm repo add coder https://helm.coder.com/
helm install coder coder/coder --namespace coder --version=1.30.0

Result

NAME PF IMAGE READY STATE INIT
timescale ● docker.io/coderenvs/timescale:1.30.0 false CrashLoopBackOff false

log

standard_init_linux.go:228: exec user process caused: exec format error │
│ Stream closed EOF for coder/timescale-0 (timescale)

**Comment by kchobantonov** [comment]
NAME                 PF            IMAGE                                                             READY          STATE                                INIT
timescale             ●             docker.io/coderenvs/timescale:1.30.0             false             CrashLoopBackOff             false  

log

 standard_init_linux.go:228: exec user process caused: exec format error                                                                                                                                                                                                                                                                                                                  │
│ Stream closed EOF for coder/timescale-0 (timescale)

**Comment by kchobantonov-runbuggy** [comment]
Yes I'm interested to get that access and give it a try.
